import type { Metadata } from 'next';
import Header from '@/components/Header';
import Footer from '@/components/Footer';

const siteUrl = process.env.NEXT_PUBLIC_SITE_URL || 'https://calcnest.me';

export const metadata: Metadata = {
  title: 'Terms of Service — CalcNest',
  description:
    'Read the CalcNest Terms of Service. By using our free online calculators, you agree to these terms and conditions.',
  alternates: {
    canonical: siteUrl + '/terms-of-service',
  },
};

export default function TermsOfServicePage() {
  return (
    <div className="min-h-screen flex flex-col bg-bg text-text">
      <Header />
      <main className="flex-grow max-w-4xl mx-auto px-4 sm:px-6 py-12 w-full">
        <h1 className="text-4xl font-heading font-bold text-accent mb-4">
          Terms of Service
        </h1>
        <p className="text-muted mb-8">Last updated: April 24, 2025</p>

        <div className="space-y-8 text-text">
          <section>
            <h2 className="text-2xl font-heading font-semibold mb-3">
              1. Acceptance of Terms
            </h2>
            <p className="text-muted leading-relaxed">
              By accessing or using the CalcNest website at{' '}
              <strong>calcnest.me</strong> (the &quot;Site&quot;), you agree to be bound by
              these Terms of Service (&quot;Terms&quot;). If you do not agree to these Terms,
              please do not use the Site. These Terms apply to all visitors, users, and
              others who access or use the Site.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-heading font-semibold mb-3">
              2. Description of Service
            </h2>
            <p className="text-muted leading-relaxed">
              CalcNest provides a suite of free online calculators including, but not
              limited to: BMI Calculator, EMI (Loan) Calculator, Percentage Calculator,
              Age Calculator, Unit Converter, and GPA Calculator. All tools are
              provided free of charge and are intended for informational and educational
              purposes only. The results generated by these calculators should not be
              used as a substitute for professional financial, medical, or academic
              advice.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-heading font-semibold mb-3">
              3. Intellectual Property
            </h2>
            <p className="text-muted leading-relaxed">
              All content on the Site, including but not limited to text, graphics,
              logos, icons, and software, is the property of CalcNest and is protected
              by applicable copyright, trademark, and other intellectual property laws.
              You may not reproduce, distribute, or create derivative works from our
              content without our express written permission.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-heading font-semibold mb-3">
              4. Disclaimer of Warranties
            </h2>
            <p className="text-muted leading-relaxed">
              THE SITE AND ALL CONTENT, TOOLS, AND SERVICES ARE PROVIDED &quot;AS IS&quot; AND
              &quot;AS AVAILABLE&quot; WITHOUT ANY WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
              INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
              PARTICULAR PURPOSE, OR NON-INFRINGEMENT. CalcNest does not warrant that
              the Site will be error-free, uninterrupted, or free of viruses or other
              harmful components. You use the Site at your own risk.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-heading font-semibold mb-3">
              5. Limitation of Liability
            </h2>
            <p className="text-muted leading-relaxed">
              To the fullest extent permitted by law, CalcNest and its operators shall
              not be liable for any indirect, incidental, special, consequential, or
              punitive damages arising from your use of, or inability to use, the Site
              or its content. This includes any financial decisions made based on
              calculator outputs, any health decisions made based on BMI results, or
              any academic decisions based on GPA calculations.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-heading font-semibold mb-3">
              6. Prohibited Uses
            </h2>
            <p className="text-muted leading-relaxed mb-4">
              You agree not to use the Site for any of the following purposes:
            </p>
            <ul className="list-disc pl-6 space-y-2 text-muted">
              <li>
                To scrape, crawl, or harvest data from the Site in an automated manner
                without prior written consent.
              </li>
              <li>
                To transmit any spam, malware, or other harmful or disruptive content.
              </li>
              <li>
                To attempt to gain unauthorized access to any part of the Site or its
                related systems.
              </li>
              <li>
                To use the Site for any commercial purpose without our express written
                permission.
              </li>
              <li>To violate any applicable local, national, or international law.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-heading font-semibold mb-3">
              7. Third-Party Links
            </h2>
            <p className="text-muted leading-relaxed">
              The Site may contain links to third-party websites. These links are
              provided for your convenience only. CalcNest has no control over the
              content of those sites and accepts no responsibility for them or for any
              loss or damage that may arise from your use of them.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-heading font-semibold mb-3">
              8. Advertising
            </h2>
            <p className="text-muted leading-relaxed">
              CalcNest displays advertisements provided by Google AdSense. These ads
              are served by third-party advertising partners and CalcNest is not
              responsible for their content. By using the Site, you acknowledge that
              you may be served personalized advertisements based on your browsing
              history. You may opt out of personalized advertising at any time via{' '}
              <a
                href="https://www.google.com/settings/ads"
                target="_blank"
                rel="noopener noreferrer"
                className="text-accent underline"
              >
                Google&apos;s Ad Settings
              </a>
              .
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-heading font-semibold mb-3">
              9. Changes to Terms
            </h2>
            <p className="text-muted leading-relaxed">
              We reserve the right to modify these Terms at any time. Changes will be
              effective immediately upon posting to the Site. Your continued use of the
              Site after any changes constitutes your acceptance of the new Terms. We
              encourage you to review these Terms periodically.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-heading font-semibold mb-3">
              10. Governing Law
            </h2>
            <p className="text-muted leading-relaxed">
              These Terms shall be governed by and construed in accordance with
              applicable laws, without regard to any conflict of law principles. Any
              disputes arising from these Terms or your use of the Site shall be
              resolved through good-faith negotiation between the parties.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-heading font-semibold mb-3">
              11. Contact Information
            </h2>
            <p className="text-muted leading-relaxed">
              If you have any questions about these Terms of Service, please contact us:
            </p>
            <ul className="list-none mt-3 space-y-1 text-muted">
              <li>
                <strong className="text-text">Website:</strong>{' '}
                <a href="/contact" className="text-accent underline">
                  calcnest.me/contact
                </a>
              </li>
              <li>
                <strong className="text-text">Email:</strong> legal@calcnest.me
              </li>
            </ul>
          </section>
        </div>
      </main>
      <Footer />
    </div>
  );
}
